ZGW-3429: Fixup! github: Release package, only on tags
The condition should be evaluated in single context {{ .. }}

The observed issue was:

    a release with the same tag name already exists: main
    Error: Process completed with exit code 1.

Change to be squashed in previous commit

Origin: https://github.com/SiliconLabs/zipgateway/pull/19
Relate-to: https://github.com/SiliconLabs/zipgateway/pull/17
Relate-to: https://github.com/SiliconLabs/zipgateway/actions/runs/10287581402/job/28470948249
Signed-off-by: Philippe Coval <philippe.coval@silabs.com>